import {stories} from './paper-stories.ts';
import {Vector3,Matrix} from '@babylonjs/core';
import './paper.css';
import {PaperWorld,type Place,type Period} from './paper-world.ts';
const icons={plane:'<path d="m3 10 18-7-7 18-3-8-8-3Z"/><path d="m11 13 10-10"/>',time:'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>',camera:'<path d="M4 7h4l2-3h4l2 3h4v13H4Z"/><circle cx="12" cy="13" r="4"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4Z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',pin:'<path d="M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 1 1 14 0Z"/><circle cx="12" cy="9" r="2"/>'};
const icon=(name:keyof typeof icons)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Mark='interest'|'want';type Photo={id:string;placeId?:string;placeName:string;clock:string;period:string;position:number[];blob:Blob;created:number};
let marks:Record<string,Mark>={};try{const raw=JSON.parse(localStorage.getItem('paper-shenzhen-marks-v1')||'{}');for(const [k,v] of Object.entries(raw))if(v==='interest'||v==='want')marks[k]=v;}catch{}
let db:IDBDatabase|null=null;let photos:Photo[]=[];let selected:Place|null=null;let target:Place|null=null;let drawer=false;let filter='saved';let hidden=false;let booted=false;let photoURLs:string[]=[];
const texts:Record<string,string>={bamboo:'把海湾的风折好，绕过一片向上的光。',tencent:'不急着抵达下一站，先沿着楼间的天空转一圈。',pingan:'把城市放在脚下，也把目光放远一点。',civic:'在屋檐与天空之间，留一点空白给今天。',lianhua:'掠过山的轮廓，让喧闹慢慢退到身后。',baypark:'沿着水与陆地的相接处，飞向更宽的风。',talent:'越过岸边的树，把一段暮色带走。',kk100:'一扇扇窗亮起来，城市又写了一页。',diwang:'旧的天际线，也是新的旅程。'};
document.querySelector('#app')!.innerHTML=`
<canvas id="flight" aria-label="深圳纸飞机三维飞行场景"></canvas>
<div id="vignette"></div>
<section id="bay-route" class="hud" aria-label="海湾慢行路线"><small>第一封来信 · 海湾慢行</small><div><button data-stop="talent"><i>01</i>人才公园</button><span>·</span><button data-stop="bamboo"><i>02</i>春笋</button><span>·</span><button data-stop="tencent"><i>03</i>腾讯滨海</button></div><p>点一处风景，读它的故事</p></section>
<div id="landmark-pins" class="hud"></div>
<header class="hud" id="top"><div class="brand">${icon('plane')}<div><strong>先抵达<span>深圳</span></strong><small>A LETTER TO THE WIND</small></div></div><nav aria-label="旅行工具"><button id="time-toggle">${icon('time')}<span id="clock">17:20</span><span id="period">黄昏</span></button><button id="photo-toggle">${icon('camera')}<span>拍照</span><kbd>P</kbd></button><button id="journey-toggle">${icon('bookmark')}<span>我的旅程</span><i id="mark-count">0</i></button></nav></header>
<section id="time-panel" class="glass popover" hidden><small>把今天停在喜欢的光里</small><div class="periods"><button data-period="dawn">清晨<small>06:20</small></button><button data-period="day">午后<small>14:00</small></button><button data-period="sunset" class="active">黄昏<small>17:20</small></button><button data-period="night">深夜<small>23:00</small></button></div><p>游戏 1 分钟 ≈ 现实 12 秒 · 非真实天文模拟</p></section>
<div id="compass" class="hud"><span>N</span><div id="bearing">350°</div><span class="compass-line"></span></div>
<div id="destination" class="hud" hidden><span id="target-direction">↑</span><span id="target-label"></span><button id="clear-target" aria-label="取消方向指引">×</button></div>
<section class="place-card hud" id="place-card"><div class="eyebrow"><span class="live-dot"></span><span id="area">南山 · 后海</span><span id="nearby">正在飞越</span></div><h1 id="place-name">中国华润大厦 · 春笋</h1><p id="place-prose">把海湾的风折好，绕过一片向上的光。</p><div class="mark-actions"><button id="interest">${icon('bookmark')}感兴趣</button><button id="want">${icon('pin')}想去</button><button id="place-detail" aria-label="查看地点详情">${icon('arrow')}</button></div></section>
<div class="flight-info hud"><span id="flight-state">顺风飞行</span><span id="altitude">200 m</span><span>游戏高度</span></div>
<footer class="hud" id="bottom"><div class="help"><span><kbd>W</kbd><kbd>S</kbd> 升降</span><span><kbd>A</kbd><kbd>D</kbd> 转向</span><span><kbd>Shift</kbd> 乘风</span><span><kbd>空格</kbd> 悬停</span><span>拖动转向</span></div><button id="about-toggle">场景与来源 ↗</button></footer>
<div class="touch hud" id="touch-controls"><button data-key="KeyW" aria-label="上升">↑</button><div><button data-key="KeyA" aria-label="左转">←</button><button data-key="KeyS" aria-label="下降">↓</button><button data-key="KeyD" aria-label="右转">→</button></div><button id="touch-hover">悬停</button><button data-key="ShiftLeft">乘风</button></div>
<aside id="journey" class="glass" hidden aria-label="我的旅程"><div class="aside-head"><div><small>KEEP A LITTLE OF SHENZHEN</small><h2>我的旅程</h2></div><button id="journey-close" class="icon-button" aria-label="关闭我的旅程">${icon('close')}</button></div><div class="tabs"><button data-tab="saved" class="active">已标记 <span id="saved-count">0</span></button><button data-tab="all">沿途地点</button><button data-tab="photos">照片 <span id="photo-count">0</span></button></div><section id="map-section"><div class="map-wrap"><canvas id="map" width="800" height="380" aria-label="压缩游戏场景地图"></canvas><span>原场景示意 · 北 ↑</span></div><p class="map-note">地图使用压缩游戏坐标，不是现实导航地图。</p><div id="selected-place"></div></section><div id="journey-content"></div><p class="local-note">只保存在此浏览器 · 无账号 · 清除浏览器数据会移除记录</p></aside>
<section id="photo-panel" class="glass" hidden><div><small>POSTCARD FROM SHENZHEN</small><h2>留住这一刻</h2><p id="photo-caption"></p></div><label>镜头远近<input id="photo-distance" type="range" min="10" max="180" value="32"></label><label>视野<input id="photo-fov" type="range" min="30" max="120" value="88"></label><p>时间已暂停 · 拖动环绕取景 · 滚轮变焦</p><div><button id="hide-ui">${icon('eye')}隐藏界面 <kbd>H</kbd></button><button id="capture" class="primary">${icon('camera')}保存照片</button><button id="photo-close">继续飞行</button></div></section>
<button id="show-ui" hidden>显示界面 · H</button>
<div id="toast" role="status" aria-live="polite"></div>
<dialog id="about"><button id="about-close" class="icon-button" aria-label="关闭说明">${icon('close')}</button><small>先抵达 / LOCAL REVIEW EDITION</small><h2>给每一个想去的人，<br>一次先抵达。</h2><p>城市底座来自 <a href="https://github.com/linranff/GTA_SZ" target="_blank" rel="noopener">linranff / GTA_SZ（深城纪）</a>。保留已有城市、道路、海岸、山体、植被与灯光；没有人物、驾驶、交通、室内或战斗系统。</p><p>只覆盖原项目已有深圳场景。游戏水平和垂直均压缩为 0.60，原点 WGS84 [114.025, 22.536]。地点真实坐标来自原项目清单；几何和高度含艺术近似，不可用于现实导航。短文为本作原创旅行随笔，不作为地标事实介绍。</p><p>原项目未提供统一代码与原创模型许可，当前仅供本地审阅，未公开发布，也不表示已获得再分发授权。地图 © OpenStreetMap contributors / ODbL；部分建筑数据 Overture / ODbL；地形 Copernicus；环境与部分植被、座椅 Poly Haven / CC0；Babylon.js / Apache-2.0。</p><p><a href="/city/LANDMARK_ATTRIBUTION.md" target="_blank">地标署名</a> · <a href="/licenses/open-city-assets.md" target="_blank">景观资产署名</a> · <a href="/licenses/coastal-terrain.md" target="_blank">海湾地形署名</a> · <a href="/ATTRIBUTION.md" target="_blank">完整来源记录</a></p><p>建议桌面浏览器与独立显卡。首次加载约 200 MB；照片存入 IndexedDB，地点标记存入 localStorage。飞行和照片时间均为虚拟时间。</p></dialog>
<section id="welcome"><div class="welcome-top">SHENZHEN · A PAPER JOURNEY<span>01 / 深圳</span></div><div class="welcome-body"><div class="paper-symbol">${icon('plane')}</div><p class="eyebrow">写给风，也写给还没出发的你</p><h1>先抵达<span>随风，去一座城。</span></h1><p class="slogan">给每一个想去的人，一次先抵达。</p><button id="begin" disabled><span id="load-text">正在展开城市</span>${icon('arrow')}</button><div class="loading-track"><span id="loading-bar"></span></div><small id="load-note">原版深圳景观 · 首次加载需要一点时间</small></div><div class="welcome-bottom"><span>没有目的地也没关系。<br>一架纸飞机，就可以出发。</span><span>南山 / 福田 / 罗湖<br>本地审阅版 · 景观与许可说明见右下角</span></div></section>`;
document.body.classList.add('boarding');
const world=new PaperWorld($<HTMLCanvasElement>('flight'));
(window as any).__paper=world;
let noticeTime=0,noticeLast='';function toast(s:string){if(s===noticeLast&&Date.now()-noticeTime<4000)return;noticeLast=s;noticeTime=Date.now();$('toast').textContent=s;$('toast').classList.add('visible');setTimeout(()=>{if(Date.now()-noticeTime>2400)$('toast').classList.remove('visible');},3000);}
world.onNotice=toast;
function saveMarks(){try{localStorage.setItem('paper-shenzhen-marks-v1',JSON.stringify(marks));return true;}catch{toast('浏览器存储不可用，标记仅在本次打开有效');return false;}}
function mark(place:Place,kind:Mark){if(marks[place.id]===kind)delete marks[place.id];else marks[place.id]=kind;saveMarks();updateCounts();renderDrawer();updatePlace();}
function updateCounts(){const n=Object.keys(marks).length;$('mark-count').textContent=String(n);$('saved-count').textContent=String(n);$('photo-count').textContent=String(photos.length);}
function openJourney(){drawer=true;world.reading=true;world.keys.clear();document.body.classList.add('reading');$('journey').hidden=false;$('time-panel').hidden=true;renderDrawer();}function closeJourney(){drawer=false;world.reading=false;world.highlight(target?.id??null);document.body.classList.remove('reading');$('journey').hidden=true;}
$('journey-toggle').onclick=()=>drawer?closeJourney():openJourney();$('journey-close').onclick=closeJourney;
$('time-toggle').onclick=()=>{$('time-panel').hidden=!$('time-panel').hidden;};
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-period]'))b.onclick=()=>{world.setPeriod(b.dataset.period as Period);syncPeriod();if(world.photo){const p=world.nearest(),name=p&&Math.hypot(p.x-world.position.x,p.z-world.position.z)<950?p.name:'深圳 · 沿途风景';$('photo-caption').textContent=`${name} · 游戏时间 ${world.clock}`;}};
function syncPeriod(){const names={dawn:'清晨',day:'午后',sunset:'黄昏',night:'深夜'};$('period').textContent=names[world.period];document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.period===world.period));}
let current:Place|null=null;let photoMapPosition:number[]|undefined;
function updatePlace(){if(!world.ready)return;current=world.nearest();if(!current)return;const distance=Math.hypot(current.x-world.position.x,current.z-world.position.z);$('area').textContent=current.area;$('place-name').textContent=distance<950?current.name:'深圳 · 沿途风景';$('nearby').textContent=distance<400?'正在飞越':distance<950?'近旁风景':'自由飞行';$('place-prose').textContent=distance<950?(texts[current.id]||'有些地方，值得让风慢一点。'):'不必为每一扇窗命名。继续飞，城市会慢慢展开。';$('interest').hidden=$('want').hidden=$('place-detail').hidden=distance>=950;for(const [id,k] of [['interest','interest'],['want','want']]){const active=marks[current.id]===k;$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active));}}
$('interest').onclick=()=>current&&mark(current,'interest');$('want').onclick=()=>current&&mark(current,'want');$('place-detail').onclick=()=>{selected=current;filter='all';openJourney();};
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-tab]'))b.onclick=()=>{filter=b.dataset.tab!;renderDrawer();};
function mapLink(p:Place){return Number.isFinite(p.lat)&&Number.isFinite(p.lon)?`https://www.openstreetmap.org/?mlat=${p.lat}&mlon=${p.lon}#map=17/${p.lat}/${p.lon}`:null;}
function renderDrawer(){if(!drawer)return;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.tab===filter));$('map-section').hidden=filter==='photos';const host=$('journey-content');host.innerHTML='';photoURLs.forEach(URL.revokeObjectURL);photoURLs=[];
 if(filter==='photos'){if(!photos.length)host.innerHTML='<div class="empty">还没有寄出的风景。<p>按 P 打开相机，把今天折成一张明信片。</p></div>';for(const p of photos){const url=URL.createObjectURL(p.blob);photoURLs.push(url);const card=document.createElement('article');card.className='photo-record';card.innerHTML=`<button class="photo-view"><img src="${url}" alt="${escape(p.placeName)} ${p.clock}" loading="lazy"></button><div><strong>${escape(p.placeName)}</strong><small>游戏时间 ${p.clock}</small></div><div class="record-actions"><button class="download">下载</button><button class="locate">地图回看</button><button class="delete">删除</button></div>`;card.querySelector<HTMLButtonElement>('.download')!.onclick=()=>download(p);card.querySelector<HTMLButtonElement>('.photo-view')!.onclick=()=>{const w=window.open();if(w){w.document.title=p.placeName;const img=w.document.createElement('img');img.src=url;img.style.width='100%';w.document.body.style.margin='0';w.document.body.append(img);}};card.querySelector<HTMLButtonElement>('.locate')!.onclick=()=>{selected=world.places.find(x=>x.id===p.placeId)||null;filter='all';photoMapPosition=p.position;renderDrawer();drawMap();toast('照片拍摄位置已标在游戏地图中');};card.querySelector<HTMLButtonElement>('.delete')!.onclick=async()=>{try{await dbOp('readwrite',s=>s.delete(p.id));photos=photos.filter(x=>x.id!==p.id);updateCounts();renderDrawer();}catch{toast('删除失败，请重试');}};host.append(card);}return;}
 const list=world.places.filter(p=>filter==='all'||marks[p.id]);if(!list.length)host.innerHTML='<div class="empty">旅程还是一张白纸。<p>把沿途地点标记为「感兴趣」或「想去」，它们就会留在这里。</p><button id="explore-places">看看沿途地点 →</button></div>';
 for(const p of list){const item=document.createElement('button');item.className='place-row'+(selected?.id===p.id?' selected':'');item.innerHTML=`<span>${icon('pin')}</span><div><strong>${escape(p.name)}</strong><small>${escape(p.area)}</small></div><em>${marks[p.id]==='want'?'想去':marks[p.id]==='interest'?'感兴趣':'↗'}</em>`;item.onclick=()=>{selected=p;photoMapPosition=undefined;renderDrawer();};host.append(item);}
 $('explore-places')?.addEventListener('click',()=>{filter='all';renderDrawer();});
 const detail=$('selected-place');detail.innerHTML='';if(selected){const p=selected,url=mapLink(p);world.highlight(p.id);detail.innerHTML=`<h3>${escape(p.name)}</h3><p>${escape(texts[p.id]||'有些地方，值得让风慢一点。')}</p><small>旅行随笔 · 非地标事实介绍</small><dl><dt>游戏位置（压缩）</dt><dd>X ${p.x.toFixed(0)} / Z ${p.z.toFixed(0)}</dd><dt>真实位置（WGS84）</dt><dd>${url?`${p.lat!.toFixed(6)}° N, ${p.lon!.toFixed(6)}° E`:'原项目未提供，暂不推算'}</dd></dl><div class="detail-actions"><button id="detail-interest" class="${marks[p.id]==='interest'?'active':''}">${marks[p.id]==='interest'?'取消兴趣':'感兴趣'}</button><button id="detail-want" class="${marks[p.id]==='want'?'active':''}">${marks[p.id]==='want'?'取消想去':'想去'}</button><button id="guide">方向指引</button>${url?`<a href="${url}" target="_blank" rel="noopener">真实地图 ↗</a>`:''}</div>`;const story=stories[p.id];if(story){const section=document.createElement('section');section.className='landmark-story';section.innerHTML=`<small>认识这处风景</small><h4>${escape(story.subtitle)}</h4><div class="story-facts">${story.facts.map(([k,v])=>`<div><small>${escape(k)}</small><strong>${escape(v)}</strong></div>`).join('')}</div><p>${escape(story.body)}</p><h5>飞行时，可以这样看</h5><p>${escape(story.look)}</p><a href="${story.url}" target="_blank" rel="noopener">资料来源 · ${escape(story.source)} ↗</a><small class="story-date">资料核对于 2026.09.16 · 建筑数据为现实尺度</small>`;detail.prepend(section);}$('detail-interest').onclick=()=>mark(p,'interest');$('detail-want').onclick=()=>mark(p,'want');$('guide').onclick=()=>{target=p;world.highlight(p.id);$('destination').hidden=false;closeJourney();toast('已标出方向 · 按 Shift 乘风前往');};}drawMap();
}
const mc=$<HTMLCanvasElement>('map'),ctx=mc.getContext('2d')!;let mapPoints:{p:Place;x:number;y:number}[]=[];
function drawMap(photoPosition:number[]|undefined=photoMapPosition){if(!world.ready)return;const [a,b,c,d]=world.data.meta.extent;const x=(v:number)=>(v-a)/(c-a)*760+20,y=(v:number)=>360-(v-b)/(d-b)*340;ctx.fillStyle='#d7e5e2';ctx.fillRect(0,0,800,380);ctx.fillStyle='#edf0e4';
 for(const poly of world.data.land){ctx.beginPath();for(const ring of poly){ring.forEach((p,i)=>i?ctx.lineTo(x(p[0]),y(p[1])):ctx.moveTo(x(p[0]),y(p[1])));ctx.closePath();}ctx.fill('evenodd');}
 ctx.strokeStyle='#c9cebf';ctx.lineWidth=1;for(const r of world.data.roads){if(!['trunk','primary','secondary'].includes(r.kind))continue;ctx.beginPath();r.points.forEach((p,i)=>i?ctx.lineTo(x(p[0]),y(p[1])):ctx.moveTo(x(p[0]),y(p[1])));ctx.stroke();}
 mapPoints=[];for(const p of world.places){if(filter==='saved'&&!marks[p.id]&&selected?.id!==p.id)continue;const px=x(p.x),py=y(p.z);mapPoints.push({p,x:px,y:py});ctx.beginPath();ctx.arc(px,py,selected?.id===p.id?9:5,0,Math.PI*2);ctx.fillStyle=selected?.id===p.id?'#b87242':marks[p.id]?'#335d55':'#8c9d91';ctx.fill();}
 const px=x(world.position.x),py=y(world.position.z);ctx.save();ctx.translate(px,py);ctx.rotate(world.yaw);ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(-6,6);ctx.lineTo(0,3);ctx.lineTo(6,6);ctx.closePath();ctx.fillStyle='#f8fbef';ctx.strokeStyle='#30544c';ctx.lineWidth=2;ctx.fill();ctx.stroke();ctx.restore();
 if(photoPosition){ctx.strokeStyle='#ae6645';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x(photoPosition[0]),y(photoPosition[2]),12,0,Math.PI*2);ctx.stroke();}
}
mc.onclick=e=>{const r=mc.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*800,y=(e.clientY-r.top)/r.height*380;const hit=mapPoints.sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(hit&&Math.hypot(hit.x-x,hit.y-y)<28){selected=hit.p;renderDrawer();}};
$('clear-target').onclick=()=>{target=null;world.highlight(null);$('destination').hidden=true;};
function togglePhoto(){if(!world.started)return;world.setPhoto(!world.photo);$('photo-panel').hidden=!world.photo;document.body.classList.toggle('photographing',world.photo);$('time-panel').hidden=true;closeJourney();if(world.photo){const nearest=world.nearest(),name=nearest&&Math.hypot(nearest.x-world.position.x,nearest.z-world.position.z)<950?nearest.name:'深圳 · 沿途风景';$('photo-caption').textContent=`${name} · 游戏时间 ${world.clock}`;$<HTMLInputElement>('photo-distance').value='32';$<HTMLInputElement>('photo-fov').value='88';}if(hidden)toggleUI();}
$('photo-toggle').onclick=togglePhoto;$('photo-close').onclick=togglePhoto;
$('photo-distance').oninput=e=>world.photoDistance=+(e.target as HTMLInputElement).value;
$('photo-fov').oninput=e=>world.camera.fov=+(e.target as HTMLInputElement).value/100;
function toggleUI(){hidden=!hidden;document.body.classList.toggle('clean',hidden);$('show-ui').hidden=!hidden;}$('hide-ui').onclick=toggleUI;$('show-ui').onclick=toggleUI;
$('about-toggle').onclick=()=>{$<HTMLDialogElement>('about').showModal();world.keys.clear();};$('about-close').onclick=()=>$<HTMLDialogElement>('about').close();
window.addEventListener('keydown',e=>{if(e.repeat||!world.started||$<HTMLDialogElement>('about').open)return;if(e.code==='KeyP')togglePhoto();if(e.code==='KeyH')toggleUI();if(e.code==='KeyJ')drawer?closeJourney():openJourney();if(e.code==='Escape'){if(hidden)toggleUI();else if(world.photo)togglePhoto();else if(drawer)closeJourney();else $('time-panel').hidden=true;}});
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);world.keys.add(b.dataset.key!);};b.onpointerup=b.onpointercancel=()=>world.keys.delete(b.dataset.key!);b.onlostpointercapture=()=>world.keys.delete(b.dataset.key!);}$('touch-hover').onclick=()=>{world.hover=!world.hover;};
function dbOp(mode:IDBTransactionMode,op:(s:IDBObjectStore)=>IDBRequest):Promise<any>{return new Promise((resolve,reject)=>{if(!db){reject(Error('storage unavailable'));return;}const tx=db.transaction('photos',mode);const req=op(tx.objectStore('photos'));let result:any;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=tx.onabort=()=>reject(tx.error);});}
async function initStorage(){try{db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('paper-shenzhen-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});photos=(await dbOp('readonly',s=>s.getAll())).sort((a:Photo,b:Photo)=>b.created-a.created);updateCounts();}catch{toast('照片存储不可用，仍可直接下载照片');}}
function download(p:Photo){const u=URL.createObjectURL(p.blob),a=document.createElement('a');a.href=u;a.download=`先抵达-${p.placeName}-${p.clock.replace(':','')}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('capture').onclick=async()=>{const button=$<HTMLButtonElement>('capture');button.disabled=true;try{world.scene.render();const source=$<HTMLCanvasElement>('flight'),c=document.createElement('canvas');c.width=source.width;c.height=source.height;const cx=c.getContext('2d')!;cx.drawImage(source,0,0);const nearest=world.nearest(),near=nearest&&Math.hypot(nearest.x-world.position.x,nearest.z-world.position.z)<950;const name=near?nearest.name:'深圳 · 沿途风景';const band=Math.max(62,c.height*.09);cx.fillStyle='rgba(246,243,232,.95)';cx.fillRect(0,c.height-band,c.width,band);cx.fillStyle='#334c47';cx.font=`${Math.max(16,c.width*.016)}px sans-serif`;cx.fillText(`先抵达 / ${name}`,c.width*.035,c.height-band*.52);cx.font=`${Math.max(11,c.width*.009)}px sans-serif`;cx.fillText(`游戏时间 ${world.clock} · 给每一个想去的人，一次先抵达。`,c.width*.035,c.height-band*.2);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('image encoding failed')),'image/jpeg',.92));const record:Photo={id:crypto.randomUUID(),placeId:near?nearest.id:undefined,placeName:name,clock:world.clock,period:world.period,position:world.position.asArray(),blob,created:Date.now()};let saved=false;try{await dbOp('readwrite',s=>s.put(record));photos.unshift(record);saved=true;updateCounts();}catch{}download(record);toast(saved?'照片已下载，也留在了「我的旅程」':'照片已下载；本地存储不可用或空间不足');}catch(e){console.error(e);toast('照片保存失败，请重试');}finally{button.disabled=false;}};
function inspectPlace(id:string){$('journey').scrollTop=0;selected=world.places.find(p=>p.id===id)??null;if(!selected)return;filter='all';openJourney();}
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-stop]'))b.onclick=()=>inspectPlace(b.dataset.stop!);
const pins=new Map<string,HTMLButtonElement>();
function updatePins(){
 for(const id of ['talent','bamboo','tencent']){
  const p=world.places.find(p=>p.id===id);if(!p)continue;
  let pin=pins.get(id);if(!pin){pin=document.createElement('button');pin.className='landmark-pin';pin.innerHTML=`<span>✧</span>${escape(p.name)}<small>读一封城市来信 ↗</small>`;pin.onclick=()=>inspectPlace(id);$('landmark-pins').append(pin);pins.set(id,pin);}
  const anchor=new Vector3(p.x,world.heightAt(p.x,p.z)+(p.height||0)+16,p.z),delta=anchor.subtract(world.camera.position);
  const viewport=world.camera.viewport.toGlobal(world.engine.getRenderWidth(),world.engine.getRenderHeight());
  const v=Vector3.Project(anchor,Matrix.Identity(),world.scene.getTransformMatrix(),viewport);
  const x=v.x/world.engine.getRenderWidth()*innerWidth,y=v.y/world.engine.getRenderHeight()*innerHeight;
  pin.hidden=world.photo||drawer||!world.started||delta.length()>1900||Vector3.Dot(delta,world.camera.getForwardRay().direction)<0||v.z<0||v.z>1||x<100||x>innerWidth-100||y<100||y>innerHeight-180;
  pin.style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;
 }
}
let tick=0;world.onTick=()=>{updatePins();if(performance.now()-tick<250)return;tick=performance.now();$('clock').textContent=world.clock;syncPeriod();$('bearing').textContent=`${Math.round((world.yaw*180/Math.PI%360+360)%360)}°`;$('altitude').textContent=`${Math.round(world.position.y)} m`;$('flight-state').textContent=world.photo?'时间暂停':world.reading?'停留 · 读一封城市来信':world.hover?'随风悬停':world.speed>70?'乘风前行':'顺风飞行';updatePlace();if(target){const distance=Math.hypot(target.x-world.position.x,target.z-world.position.z);$('target-label').textContent=`${target.name} · ${(distance/1000).toFixed(1)} km（游戏距离）`;const angle=Math.atan2(target.x-world.position.x,target.z-world.position.z)-world.yaw;$('target-direction').style.transform=`rotate(${angle}rad)`;}if(drawer&&filter!=='photos')drawMap();};
$('begin').onclick=()=>{if(!booted){location.reload();return;}world.started=true;document.body.classList.remove('boarding');$('welcome').classList.add('departed');setTimeout(()=>$('welcome').hidden=true,900);toast('轻推 W/S 升降，A/D 转向。空格可以悬停。');};
async function boot(){void initStorage();let step=0;try{await world.init(text=>{$('load-text').textContent=text;$('loading-bar').style.width=`${Math.min(92,++step*16)}%`;});booted=true;$('loading-bar').style.width='100%';$('load-text').textContent='把自己交给风';$<HTMLButtonElement>('begin').disabled=false;$('load-note').textContent='点击出发 · 推荐使用键盘与鼠标';updatePlace();}catch(e){console.error(e);$('load-text').textContent='重新展开城市';$('load-note').textContent=`加载未完成：${e instanceof Error?e.message:String(e)}。请使用本地 HTTP 服务打开。`;$<HTMLButtonElement>('begin').disabled=false;}}void boot();
